
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: kunge2013.top:8848
#        server-addr: localhost:8848


server:
  port: 8087

#
#nacos:
#  config:
#    server-addr: kunge2013.top:8848
#    data-id: nacos_config
#    type: properties
#    bootstrap:
#      log-enable: true
#    namespace: dev

logging:
  level:
    com.alibaba.nacos: debug
