
spring:
  application:
    name: registry

nacos:
  discovery:
#    server-addr: kunge2013.top:8848
    server-addr: localhost:8848
#    namespace: dev
logging:
  level:
    com.alibaba.nacos: debug

server:
  port: 8087